### ISSUE TITLE
internal error: evacuate(static): strange closure type 0

### ISSUE THREAD

**Issue by RyanGlScott** [osa1/ghc#2]
If you use this branch to build GHC, compile [`nofib`](https://github.com/iu-parfunc/nofib) with `-XStrictData` enabled and then run the [`circsim`](https://github.com/iu-parfunc/nofib/blob/9dda08a2bdda3a0beb07b4a4fb13b6a624894954/spectral/circsim/Main.lhs) program, stuff explodes:

```
./circsim +RTS -H30m -RTS 8 1000 < /dev/null
circsim: internal error: evacuate(static): strange closure type 0
   (GHC version 8.1.20160130 for x86_64_unknown_linux)
   Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

This does not happen with GHC 8.0.1-rc1 with `-XStrictData`. I'm not sure if this is due to your changes or not, so I'm also going to try building GHC with commit 54128992b2ae8b18816e74fd02bc49833dda031e (the last non-unboxed-sums-related commit) to see if I can reproduce the error with that.

**Comment by RyanGlScott** [comment]
I can confirm that this error does not occur with https://github.com/osa1/ghc/commit/54128992b2ae8b18816e74fd02bc49833dda031e.

**Comment by osa1** [comment]
Ryan, you used exactly the same build.mk settings when compiling this branch and 5412899, right?

**Comment by RyanGlScott** [comment]
Yes, I copied `mk/build.mk.sample` to `mk/build.mk` each time (i.e., release settings).

**Comment by RyanGlScott** [comment]
For reference, here is the exact flag combination I used to compile `circsim`:

```
ghc -O2 -Rghc-timing -H32m -hisuf hi -XStrictData -DSTRICT_DATA -rtsopts -c Main.lhs -o Main.o
```

And to run it:

```
./circsim +RTS -H30m -RTS 8 1000 < /dev/null
```

**Comment by osa1** [comment]
@RyanGlScott could you pull the repo and try again? I don't know how exactly, but seems like beefd477f2660386f1d7f54a398cc1f8728e0dbb may have fixed it.

**Comment by RyanGlScott** [comment]
I don't believe we've managed to reproduce this in a while, so closing for now.
